/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lecture_Mgmt_System;

import java.util.ArrayList;
import org.joda.time.DateTime;

public class App {

    public static void main(String[] args) {
        Student student = new Student("Danny Bath", "20-02-1998");
        Student student2 = new Student("John Bonham", "13-01-1994");
        Student student3 = new Student("Danny Carey", "14-08-1962");
        ArrayList<Student> students = new ArrayList<>();
        students.add(student);
        students.add(student2);
        students.add(student3);
       
        Lecturer lecturer = new Lecturer("Michael Shukat", "25-07-1974");
     
        Module module = new Module("Software Engineering", "CT417");
        module.setLecturer(lecturer);     
        Module module2 = new Module("Machine Learning", "CT419");
        module2.setLecturer(lecturer);
        Module module3 = new Module("Information Retrieval", "CT420");
        module3.setLecturer(lecturer);
        ArrayList<Module> modules = new ArrayList<>();
        modules.add(module);
        modules.add(module2);
        modules.add(module3);
                
        Course course = new Course("4BCT");
        DateTime start = new DateTime(2022, 9, 6, 0, 0, 0);
        DateTime end = new DateTime(2023, 5, 20, 0, 0, 0);
        course.setStartDate(start);
        course.setEndDate(end);
        course.addModules(modules);
        course.addStudents(students);
        
        ArrayList<Course> courses = new ArrayList<>();
        courses.add(course);
        module.addCourses(courses);
        module2.addCourses(courses);
        module3.addCourses(courses);
        module.addStudents(students);
        module2.addStudents(students);
        module3.addStudents(students);
        
        student.addCourses(courses);
        student2.addCourses(courses);
        student3.addCourses(courses);
        student.addModules(modules);
        student2.addModules(modules);
        student3.addModules(modules);
        
        
        System.out.println(course);
        
        for (Module x : modules) {
            System.out.println(x);
        }

        for (Student x : students) {
            System.out.println(x);
        }
        
      
    }
}
